/** English-only CTA button labels — stable across UI languages. */
export const CTA = {
  landing: {
    startJapa: 'Start Japa',
    tryJapa: 'Try Japa',
    tryJapaNoLoginHint: '(No Login)',
  },
  menu: {
    allDevatasJapa: 'All Devatas',
    specials: 'Specials',
    istaDevata: 'Ista Devata',
    signIn: 'Sign in',
  },
  game: {
    back: '← Back',
    pause: 'Pause',
    exit: 'Exit',
    resume: 'Resume',
    startFresh: 'Start fresh',
    startFreshConfirmYes: 'Yes, delete saved progress',
    startFreshConfirmNo: 'No, keep my progress',
    playNameSave: 'Save & play',
    playNameSaving: 'Saving…',
    nextLevel: 'Next Level',
    restart: 'Restart',
    menu: 'Menu',
    watchForMoves: 'Watch for +5 moves',
    continue: 'Continue',
    continueAsGuest: 'Continue as guest',
    watchForLife: 'Watch ad for +1 life',
    buyLives: (price: number) => `Buy lives (₹${price})`,
    refreshBoard: 'No matches? Refresh board',
    generating: 'Generating…',
    weeklyStreakDownload: 'Download week progress card',
    weeklyStreakHandwriting: 'Handwritten 108 PDF (Japa count)',
    special108Handwriting: 'Handwritten 108 PDF (Japa count)',
    birthdayGreeting: 'Download birthday greeting',
    japaCard: 'Download Japa Card',
    creatingGreeting: 'Creating greeting…',
  },
  levelGate: {
    alreadyCompleteOk: 'Back to level map',
    getPro: 'Get Pro to continue',
    later: 'Later',
  },
  paywall: {
    later: 'Later',
    opening: 'Opening…',
  },
  plans: {
    signInToPayPro: 'Sign in to pay Pro',
    ctaPro: 'Pay Monthly Dakshina (Pro)',
    ctaPremium: 'Offer Premium Dakshina',
  },
  specials: {
    japa108Start: 'Start 108 Japa',
    pushpaAradhana: 'Pushpa Aradhana',
    hub108OneTime: 'One session',
    hub108Weekly: 'Weekly streak',
    hub108WeeklyHint: 'Mon–Sun IST',
    hubCounterManual: 'One by one',
    hubCounterAuto: 'Auto',
    hubCounterAutoHint: 'Up to 108',
    hubPushpaBlurb: 'Digital flower offerings',
    japamCounterReset: 'Reset count',
    autoStart: 'Start auto japa',
    autoStop: 'End & save',
    autoComplete: 'Complete & save 108',
    autoSaveSession: 'Save japas',
    japamCounterTap: 'Japa',
    twoPlayerGame: 'Two Player Game',
    anniversaryComingSoonHint: 'Anniversary · Coming soon',
  },
  occasions: {
    coupleNextLevel: 'Next level',
    downloadPdf: 'Download summary (PDF)',
    resumeCoupleGame: 'Resume game',
    leavePausedSession: 'Leave (session stays paused)',
  },
  common: {
    reload: 'Reload',
    ok: 'OK',
    loading: 'Loading…',
  },
} as const;
